//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        public int Id { get; set; }
        public int MusteriId { get; set; }
        public int AracId { get; set; }
        public int Tutar { get; set; }
        public System.DateTime AlimTarihi { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
        public int TahminiKm { get; set; }
        public string Durum { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
